[package]
name = "huskarl-reqwest"
version = "0.7.0"
edition = "2024"
rust-version = "1.92"
description = "reqwest support for huskarl (OAuth2 client) ecosystem."
repository = "https://github.com/huskarl-rs/huskarl"
license = "MIT OR Apache-2.0"
keywords = ["oauth2", "security", "authentication"]
categories = ["authentication"]
readme = "README.md"

[features]
rustls-tls = ["reqwest/rustls"]
native-tls = ["reqwest/native-tls"]

[dependencies]
bon = { version = "3", default-features = false }
bytes = { version = "1", default-features = false }
http = { version = "1", default-features = false }
huskarl-core = { workspace = true }
reqwest = { version = "0.13", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
