[workspace]
resolver = "3"
members = ["huskarl", "huskarl-core", "huskarl-macros", "huskarl-resource-server"]
exclude = ["integration"]

[workspace.dependencies]
huskarl-core = { version = "0.3" }
huskarl-macros = { version = "0.1" }
huskarl-reqwest = { version = "0.3" }
huskarl-crypto-native = { version = "0.4" }
huskarl-crypto-webcrypto = { version = "0.3" }

bon = { version = "3.9", default-features = false, features = [
  "experimental-generics-setters",
  "experimental-overwritable",
  "implied-bounds",
] }
form_urlencoded = { version = "1", default-features = false, features = ["std"] }
rand = { version = "0.10", default-features = false, features = ["std", "sys_rng", "thread_rng"] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
sha2 = { version = "0.11", default-features = false }
snafu = { version = "0.9", default-features = false, features = ["rust_1_81", "std"] }
metrics = { version = "0.24", default-features = false }
url = { version = "2", default-features = false }
