[package]
name = "huskarl-conformance"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[features]
# Enables integration tests that require a running OpenID conformance suite instance.
# See README for setup instructions.
conformance-suite-tests = []

[dependencies]
bytes = { workspace = true, features = ["std"] }
http = { workspace = true, features = ["std"] }
huskarl = { workspace = true, features = ["url", "authorization-flow-loopback"] }
huskarl-reqwest = { workspace = true, features = ["rustls-tls"] }
reqwest = { workspace = true, features = ["cookies", "json", "query"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "macros", "time"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
bon = { workspace = true }
huskarl-crypto-native = { workspace = true }
huskarl-testkit = { path = "../huskarl-testkit" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
