[package]
name = "huskarl-macros"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
description = "Procedural macros for the huskarl OAuth2 client library."
repository = "https://github.com/huskarl-rs/huskarl"
license = "MIT OR Apache-2.0"
readme = "README.md"

[lib]
proc-macro = true
doc = false

[dependencies]
darling = "0.23"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
insta = "1"
prettyplease = "0.2"
trybuild = { version = "1", features = ["diff"] }
