[package]
name = "huskarl-macros"
version = "0.4.0"
edition = "2024"
rust-version = "1.92"
description = "Procedural macros for the huskarl OAuth2 ecosystem."
repository = "https://github.com/huskarl-rs/huskarl"
homepage = "https://github.com/huskarl-rs/huskarl"
documentation = "https://docs.rs/huskarl-macros"
license = "MIT OR Apache-2.0"
readme = "README.md"

[lib]
proc-macro = true
doc = false

[dependencies]
darling = "0.24.1"
proc-macro2 = "1.0.91"
proc-macro-crate = "3"
quote = "1.0.37"
syn = { version = "3.0.3", features = ["full"] }

[dev-dependencies]
bon = { workspace = true }
huskarl-core = { path = "../huskarl-core" }
rustversion = "1.0.6"
trybuild = { version = "1.0.86", features = ["diff"] }
