[workspace]
resolver = "2"
members = ["huskarl-testkit", "huskarl-conformance"]

[patch.crates-io]
huskarl-core = { path = "../huskarl-core" }
huskarl = { path = "../huskarl" }
huskarl-crypto-native = { path = "../../huskarl-crypto-native" }
huskarl-reqwest = { path = "../../huskarl-reqwest" }

[workspace.dependencies]
bon = { version = "3.9", default-features = false, features = [
  "experimental-generics-setters",
  "experimental-overwritable",
  "implied-bounds",
] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
