//! Server-side `DPoP` nonce enforcement (RFC 9449 §8).
//!
//! A `DPoP` nonce is a server-chosen value the client must echo in its next
//! proof, letting the server control proof freshness and limit replay. Both
//! server roles issue them: an authorization server at the token endpoint
//! (§8) and a resource server on protected resources (§8.2). Implement
//! [`DPoPNonceChecker`] to issue and validate nonces, or use the
//! batteries-included [`SealedTimestampNonce`], which encodes the issue time
//! in an AEAD-sealed token and so needs no server-side state.

use std::sync::Arc;

use bon::Builder;

use crate::{
    crypto::cipher::AeadSealerUnsealer,
    error::{Error, ErrorKind},
    platform::{Duration, MaybeSendBoxFuture, MaybeSendSync, SystemTime},
};

/// The outcome of a `DPoP` nonce check.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NonceCheck {
    /// The nonce is valid and fresh — no action needed.
    Valid,
    /// The nonce is valid but approaching expiry — include the new nonce in the response
    /// so the client can use it on the next request.
    ValidWithNewNonce(String),
    /// The nonce is missing, invalid, or expired. Reject the request with
    /// `use_dpop_nonce` and include the provided nonce in the response.
    Invalid(String),
}

/// Validates `DPoP` nonces presented by clients.
///
/// Implement this trait to enforce nonce-based replay protection on `DPoP` proofs,
/// as described in RFC 9449 §8.
///
/// This trait is dyn-capable: validators store it as `Arc<dyn DPoPNonceChecker>`.
/// Write the method body as `Box::pin(async move { ... })`.
pub trait DPoPNonceChecker: MaybeSendSync {
    /// Checks whether the presented nonce is valid.
    ///
    /// Returns a [`NonceCheck`] indicating whether the nonce is valid, approaching
    /// expiry, or invalid, along with any new nonce to include in the response.
    fn check_nonce<'a>(
        &'a self,
        nonce: Option<&'a str>,
    ) -> MaybeSendBoxFuture<'a, Result<NonceCheck, Error>>;
}

impl<T: DPoPNonceChecker + ?Sized> DPoPNonceChecker for &T {
    fn check_nonce<'a>(
        &'a self,
        nonce: Option<&'a str>,
    ) -> MaybeSendBoxFuture<'a, Result<NonceCheck, Error>> {
        (**self).check_nonce(nonce)
    }
}

impl<T: DPoPNonceChecker + ?Sized> DPoPNonceChecker for Box<T> {
    fn check_nonce<'a>(
        &'a self,
        nonce: Option<&'a str>,
    ) -> MaybeSendBoxFuture<'a, Result<NonceCheck, Error>> {
        (**self).check_nonce(nonce)
    }
}

impl<T: DPoPNonceChecker + ?Sized> DPoPNonceChecker for Arc<T> {
    fn check_nonce<'a>(
        &'a self,
        nonce: Option<&'a str>,
    ) -> MaybeSendBoxFuture<'a, Result<NonceCheck, Error>> {
        (**self).check_nonce(nonce)
    }
}

/// A [`DPoPNonceChecker`] that issues and validates AEAD-encrypted timestamp nonces.
///
/// Nonces are generated by encrypting the current Unix timestamp with an AEAD cipher,
/// then base64url-encoding the result (without padding). This allows stateless verification of nonce age
/// without a database, as long as the encryption key is stable across requests.
#[derive(Debug, Builder)]
pub struct SealedTimestampNonce {
    /// The AEAD sealer/unsealer for nonce timestamps — one object that seals on
    /// the way out and unseals on the way in.
    ///
    /// Wrap an [`AeadCipher`](crate::crypto::cipher::AeadCipher) (a key,
    /// or a rotating stack such as
    /// [`ScheduledRefreshCipher`](crate::crypto::cipher::ScheduledRefreshCipher))
    /// in [`AeadV1Cipher`](crate::crypto::cipher::AeadV1Cipher); an
    /// externally-managed sealer (e.g. a KMS encrypt endpoint) can implement
    /// the traits directly.
    ///
    /// The nonce key is long-lived with no natural rotation trigger — prefer a
    /// wide-nonce cipher (XChaCha20-Poly1305, `XC20P`) over AES-GCM's 2^32
    /// per-key encryption budget; see [composing crypto
    /// strategies](crate::_docs::explanation::crypto_strategies).
    #[builder(with = |sealer: impl AeadSealerUnsealer + 'static| Arc::new(sealer) as Arc<dyn AeadSealerUnsealer>)]
    sealer: Arc<dyn AeadSealerUnsealer>,
    /// The maximum age of a valid nonce. Defaults to 1 hour.
    #[builder(into, default = Duration::from_hours(1))]
    nonce_lifetime: Duration,
    /// How far before expiry a still-valid nonce triggers proactive rotation.
    /// Defaults to 15 minutes.
    #[builder(into, default = Duration::from_mins(15))]
    renewal_window: Duration,
    /// AEAD associated data bound into every nonce. The default is fine; change
    /// it only for domain separation, and keep it stable across requests (seal
    /// and unseal must use the same value).
    #[builder(into, default = b"dpop-nonce")]
    aad: Vec<u8>,
}

impl SealedTimestampNonce {
    async fn generate_nonce(&self) -> Result<String, Error> {
        use base64::prelude::*;
        let current_time = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .map_err(|e| Error::new(ErrorKind::DPoP, e))?
            .as_secs()
            .to_be_bytes();
        // `seal` freezes one key snapshot per nonce, even under rotation. The
        // kid is dropped: a nonce is opaque to the client that echoes it back,
        // so unsealing relies on try-all instead.
        let sealed = self.sealer.seal(&current_time, &self.aad).await?;
        Ok(BASE64_URL_SAFE_NO_PAD.encode(sealed.bundle))
    }

    async fn nonce_age_secs(&self, nonce: Option<&str>) -> Option<u64> {
        use base64::prelude::*;
        let nonce_bytes = BASE64_URL_SAFE_NO_PAD.decode(nonce?).ok()?;
        let unsealed_bytes = self
            .sealer
            .unseal(&nonce_bytes, &self.aad, None)
            .await
            .ok()?;
        let timestamp_bytes = <[u8; 8]>::try_from(unsealed_bytes).ok()?;
        let nonce_issued_at = u64::from_be_bytes(timestamp_bytes);
        let current_secs = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .ok()?
            .as_secs();
        Some(current_secs.saturating_sub(nonce_issued_at))
    }
}

impl DPoPNonceChecker for SealedTimestampNonce {
    fn check_nonce<'a>(
        &'a self,
        nonce: Option<&'a str>,
    ) -> MaybeSendBoxFuture<'a, Result<NonceCheck, Error>> {
        Box::pin(async move {
            let lifetime = self.nonce_lifetime.as_secs();
            let renewal_threshold = lifetime.saturating_sub(self.renewal_window.as_secs());

            match self.nonce_age_secs(nonce).await {
                Some(age) if age <= lifetime => {
                    if age >= renewal_threshold {
                        Ok(NonceCheck::ValidWithNewNonce(self.generate_nonce().await?))
                    } else {
                        Ok(NonceCheck::Valid)
                    }
                }
                _ => Ok(NonceCheck::Invalid(self.generate_nonce().await?)),
            }
        })
    }
}

#[cfg(test)]
mod tests {
    use std::borrow::Cow;

    use base64::prelude::*;

    use super::*;
    use crate::crypto::{
        KeyMatchStrength,
        cipher::{
            AeadEncryptor, AeadOutput, AeadSealer as _, AeadV1Cipher, CipherMatch, DecryptError,
        },
    };

    #[derive(Debug)]
    struct MockEncryptor;

    /// XOR "cipher" with both capabilities on one object — the shape a
    /// symmetric key or KMS-backed cipher provides: a selector handing out its
    /// shared inner encryptor, plus a decryptor.
    #[derive(Debug)]
    struct MockCipher {
        inner: Arc<MockEncryptor>,
    }

    impl MockCipher {
        fn new() -> Self {
            Self {
                inner: Arc::new(MockEncryptor),
            }
        }
    }

    impl crate::crypto::cipher::AeadEncryptor for MockEncryptor {
        fn enc_algorithm(&self) -> Cow<'_, str> {
            "mock".into()
        }

        fn key_id(&self) -> Option<Cow<'_, str>> {
            None
        }

        fn encrypt<'a>(
            &'a self,
            plaintext: &'a [u8],
            _aad: &'a [u8],
        ) -> MaybeSendBoxFuture<'a, Result<AeadOutput, Error>> {
            Box::pin(async move {
                Ok(AeadOutput {
                    nonce: vec![1, 2, 3],
                    ciphertext: plaintext.iter().map(|b| b ^ 0xFF).collect(),
                    tag: vec![4, 5, 6, 7],
                })
            })
        }
    }

    impl crate::crypto::cipher::AeadEncryptorSelector for MockCipher {
        fn select_encryptor(&self) -> MaybeSendBoxFuture<'_, Arc<dyn AeadEncryptor>> {
            let snapshot: Arc<dyn AeadEncryptor> = self.inner.clone();
            Box::pin(async move { snapshot })
        }
    }

    impl crate::crypto::cipher::AeadDecryptor for MockCipher {
        fn cipher_match(&self, _m: &CipherMatch<'_>) -> Option<KeyMatchStrength> {
            Some(KeyMatchStrength::ByAlgorithm)
        }

        fn decrypt<'a>(
            &'a self,
            _cipher_match: Option<&'a CipherMatch<'a>>,
            _nonce: &'a [u8],
            ciphertext: &'a [u8],
            _tag: &'a [u8],
            _aad: &'a [u8],
        ) -> MaybeSendBoxFuture<'a, Result<Vec<u8>, DecryptError>> {
            Box::pin(async move { Ok(ciphertext.iter().map(|b| b ^ 0xFF).collect()) })
        }
    }

    fn checker() -> SealedTimestampNonce {
        SealedTimestampNonce::builder()
            .sealer(AeadV1Cipher::new(MockCipher::new()))
            .build()
    }

    /// Forge a nonce whose sealed timestamp lies `age_secs` in the past.
    async fn nonce_with_age(checker: &SealedTimestampNonce, age_secs: u64) -> String {
        let issued_at = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_secs()
            - age_secs;
        let sealed = checker
            .sealer
            .seal(&issued_at.to_be_bytes(), &checker.aad)
            .await
            .unwrap();
        BASE64_URL_SAFE_NO_PAD.encode(sealed.bundle)
    }

    #[tokio::test]
    async fn missing_nonce_is_invalid_and_issues_one_that_validates() {
        let checker = checker();
        let NonceCheck::Invalid(new_nonce) = checker.check_nonce(None).await.unwrap() else {
            panic!("missing nonce must be Invalid");
        };
        assert_eq!(
            checker.check_nonce(Some(&new_nonce)).await.unwrap(),
            NonceCheck::Valid
        );
    }

    #[tokio::test]
    async fn garbage_nonce_is_invalid() {
        let checker = checker();
        assert!(matches!(
            checker.check_nonce(Some("not-a-nonce")).await.unwrap(),
            NonceCheck::Invalid(_)
        ));
    }

    #[tokio::test]
    async fn expired_nonce_is_invalid() {
        let checker = checker();
        let old = nonce_with_age(&checker, 3601).await;
        assert!(matches!(
            checker.check_nonce(Some(&old)).await.unwrap(),
            NonceCheck::Invalid(_)
        ));
    }

    #[tokio::test]
    async fn nonce_in_renewal_window_rotates() {
        let checker = checker();
        let aging = nonce_with_age(&checker, 3000).await; // past the 2700s renewal threshold
        assert!(matches!(
            checker.check_nonce(Some(&aging)).await.unwrap(),
            NonceCheck::ValidWithNewNonce(_)
        ));
    }
}
